# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: release

on: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  DOCKER_IMAGE: ranma2913/echo-api

jobs:
  build-release:
    needs: 'semver-bump'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: git-describe
        run: echo "DOCKER_TAG=$(git describe --tags --always --match "v[0-9]*.[0-9]*.[0-9]*" 2>/dev/null || echo 'v0.0.0')" >> "$GITHUB_ENV"

      - name: maven-package-native
        run: |
          ./mvnw -B package -Pnative \
          -Dspring-boot.build-image.imageName=${{ env.DOCKER_IMAGE }} \
          -Dspring-boot.build-image.tag=${{ env.DOCKER_TAG }}

      - name: docker-image-inspect
        run: |
          docker image inspect ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }} # https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context
          password: ${{ secrets.DOCKER_PASSWORD }} # https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context

      - name: docker-push
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
