name: release

on: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  DOCKER_IMAGE: docker.io/ranma2913/echo-api

# Cancel currently running workflow if we get a new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: git-describe
        run: echo "DOCKER_TAG=$(git describe --tags --always --match "v[0-9]*.[0-9]*.[0-9]*" 2>/dev/null || echo 'v0.0.0')" >> "$GITHUB_ENV"

      - name: maven-package-native
        run: |
          ./mvnw -B package -Pnative \
          -Dspring-boot.build-image.imageName=${{ env.DOCKER_IMAGE }} \
          -Dspring-boot.build-image.tag=${{ env.DOCKER_TAG }}

      - name: docker-image-inspect
        run: |
          docker image inspect ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }} # https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context
          password: ${{ secrets.DOCKER_PASSWORD }} # https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context

      - name: docker-push
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
